WITH CUSTOMERSUMMARY AS (
	SELECT
		[Customer_ID],
		MAX([InvoiceDate]) AS LASTPURCHASEDATE,
		COUNT(DISTINCT [Invoice]) AS FREQUENCY,
		SUM([Quantity] * [Price]) AS MONETARY
		FROM VW_CLEAN_DATA_
		GROUP BY [Customer_ID]
),
MAXDATECTE AS (
	SELECT MAX([InvoiceDate]) AS DATASETMAXDATE FROM VW_CLEAN_DATA_
)
SELECT
	C.[Customer_ID],
	DATEDIFF(DAY,C.LASTPURCHASEDATE,M.DATASETMAXDATE) AS RECENCY,
	C.FREQUENCY,
	C.MONETARY,
	CASE
		WHEN DATEDIFF(DAY,C.LASTPURCHASEDATE,M.DATASETMAXDATE)>30 THEN 1
		ELSE 0
	END AS IS_CHURN
FROM CUSTOMERSUMMARY C
CROSS JOIN MAXDATECTE M